#DROP DATABASE modula;

CREATE DATABASE IF NOT EXISTS modula;
use modula;

CREATE TABLE IF NOT EXISTS contacts (
	id INT(5) AUTO_INCREMENT PRIMARY KEY,
	nom VARCHAR(50) NOT NULL,
	prenom VARCHAR(50) NOT NULL,
	email VARCHAR(50) NOT NULL,
	message TEXT NOT NULL,
	RGPD BOOLEAN NOT NULL,
	date date NOT NULL,
	heure time NOT NULL,
	ip VARCHAR(15) NOT NULL
);

CREATE TABLE IF NOT EXISTS login (
	id INT(5) AUTO_INCREMENT PRIMARY KEY,
	login VARCHAR(20) NOT NULL,
	mdp VARCHAR(20) NOT NULL
);
